services:

  prometheus:
    image: prom/prometheus:latest
    container_name: cdn-prometheus

    ports:
      - "9090:9090"

    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus

    restart: unless-stopped


  grafana:
    image: grafana/grafana:latest
    container_name: cdn-grafana

    ports:
      - "3000:3000"

    volumes:
      - grafana-data:/var/lib/grafana

    depends_on:
      - prometheus

    restart: unless-stopped


volumes:
  prometheus-data:
  grafana-data: